stages:
  - build

variables:
  DOCKER_BUILDKIT: 1

# Build Docker image
build:
  stage: build
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
  script:
    - |
      # Determine which version tag to use
      if [ -n "$VERSION_TAG" ]; then
        TAG_VERSION="$VERSION_TAG"
      elif [ -n "$CI_COMMIT_TAG" ]; then
        TAG_VERSION="$CI_COMMIT_TAG"
      fi

      # Build base command with common outputs
      BUILD_CMD="buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --output type=image,name=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA,push=true \
        --output type=image,name=$CI_REGISTRY_IMAGE:latest,push=true"

      # Add version tag if available
      if [ -n "$TAG_VERSION" ]; then
        BUILD_CMD="$BUILD_CMD --output type=image,name=$CI_REGISTRY_IMAGE:$TAG_VERSION,push=true"
      fi

      # Execute build
      eval $BUILD_CMD
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
